### ISSUE TITLE
How to mine the text ?

### ISSUE THREAD

**Issue by ltetrel** [brainhack-school2020/koudyk_bhs_project#3]
Hi @koudyk,

Congrats for this project description!

What type of methods are you planning to use for text mining ? Are you planning to use [word2vec](https://www.tensorflow.org/tutorials/text/word_embeddings) for example ?

**Comment by koudyk** [comment]
Hi @ltetrel! 

Thanks for the question! I think I'd like to focus more on packaging, testing, and interacting with the PubMed API, so right now I'm planning to have a very simple method of text mining - just searching for 'Python' and 'Matlab'. 

If I get a package working and tested with time to spare, I might look into using something more complicated like word2vec. Thanks for the idea!
