### ISSUE TITLE
Tools for extracting features from text files in Python

### ISSUE THREAD

**Issue by jogaru1818** [brainhack-school2020/koudyk_bhs_project#4]
Hello @koudyk I'm very interested in the results from your project! Indeed that is a very worrying issue in neuroimaging.  A big paper on that topic was published yesterday in Nature https://www.nature.com/articles/s41586-020-2314-9  maybe it could be helpful.
Here's also an article about some usefull way to extract features from text files using python
https://www.analyticsvidhya.com/blog/2018/02/the-different-methods-deal-text-data-predictive-python/

**Comment by koudyk** [comment]
Hi @jogaru1818, glad it sounds interesting! Some people in my lab contributed to that paper, so I did know about it, but it was a great thought to share it - it's right up my ally. 

And thanks for sharing the article on text mining; I'm newer to text mining, so it'll be a useful resource. Thanks :)
